name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [16, 20]
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - name: Get Code
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependecies
      run: npm ci
    - name: build project
      run: npm run build
